import type { Card } from "./cards";

export const minorArcana: Card[] = [
  // ── WANDS ──────────────────────────────────────────────────────────────
  {
    id: "wands-ace",
    number: null,
    name: "Ace of Wands",
    name_ja: "ワンドのエース",
    aliases: ["AW", "WA", "W1", "1W", "ace of wands", "ワンドのエース"],
    upright: {
      keywords_ja: "情熱の始まり、創造力、新しい挑戦",
      detail_ja: "新しいプロジェクトや冒険への純粋な情熱とエネルギーが湧き上がっています。行動を起こす絶好の機会です。",
      detail_en: "New beginnings, creative spark, inspiration, potential.",
    },
    reversed: {
      keywords_ja: "エネルギー不足、遅延、創造性のブロック",
      detail_ja: "やる気が出ない、または始めたいことを先延ばしにしている状態です。タイミングを見直す必要があるかもしれません。",
      detail_en: "Delays, lack of motivation, creative blocks.",
    },
  },
  {
    id: "wands-2",
    number: null,
    name: "Two of Wands",
    name_ja: "ワンドの2",
    aliases: ["W2", "2W", "2 of wands", "ワンドの2"],
    upright: {
      keywords_ja: "計画、将来のビジョン、大胆な決断",
      detail_ja: "世界を見渡す視点で長期的な計画を立てています。大きな可能性が目の前に広がっています。",
      detail_en: "Future planning, progress, decisions, discovery.",
    },
    reversed: {
      keywords_ja: "計画の失敗、恐れ、安全地帯への固執",
      detail_ja: "未知への恐れから一歩踏み出せない状態です。せっかくの計画が実行に移せていません。",
      detail_en: "Fear of unknown, lack of planning, bad news.",
    },
  },
  {
    id: "wands-3",
    number: null,
    name: "Three of Wands",
    name_ja: "ワンドの3",
    aliases: ["W3", "3W", "3 of wands", "ワンドの3"],
    upright: {
      keywords_ja: "展望、進歩、遠くへの視野",
      detail_ja: "すでに行動を起こし、成果が出始めています。さらなる展望と可能性を見据えながら前進しています。",
      detail_en: "Progress, expansion, foresight, overseas opportunities.",
    },
    reversed: {
      keywords_ja: "障害、遅延、帰国",
      detail_ja: "予期せぬ障害や遅延が発生しています。計画の見直しが必要かもしれません。",
      detail_en: "Obstacles, delays, frustration, lack of foresight.",
    },
  },
  {
    id: "wands-4",
    number: null,
    name: "Four of Wands",
    name_ja: "ワンドの4",
    aliases: ["W4", "4W", "4 of wands", "ワンドの4"],
    upright: {
      keywords_ja: "祝祭、調和、家庭の安定",
      detail_ja: "目標達成を祝うひとときです。家族や仲間と共に喜びを分かち合う平和で安定した時期です。",
      detail_en: "Celebration, harmony, marriage, home, community.",
    },
    reversed: {
      keywords_ja: "不安定、家庭内の問題、祝祭の延期",
      detail_ja: "家庭や人間関係に不安定さが生じています。期待していた祝いが先送りになる可能性があります。",
      detail_en: "Lack of harmony, unstable home, delayed celebrations.",
    },
  },
  {
    id: "wands-5",
    number: null,
    name: "Five of Wands",
    name_ja: "ワンドの5",
    aliases: ["W5", "5W", "5 of wands", "ワンドの5"],
    upright: {
      keywords_ja: "競争、葛藤、対立",
      detail_ja: "さまざまな意見や力がぶつかり合っています。混乱の中にも成長のチャンスが隠れています。",
      detail_en: "Conflict, competition, tension, diversity of opinion.",
    },
    reversed: {
      keywords_ja: "対立の回避、内なる葛藤、平和の模索",
      detail_ja: "争いを避けようとしているか、または内部の葛藤を抱えています。妥協点を見つける時です。",
      detail_en: "Avoiding conflict, inner tension, compromise.",
    },
  },
  {
    id: "wands-6",
    number: null,
    name: "Six of Wands",
    name_ja: "ワンドの6",
    aliases: ["W6", "6W", "6 of wands", "ワンドの6"],
    upright: {
      keywords_ja: "勝利、成功、公の称賛",
      detail_ja: "努力が実を結び、周囲から認められる成功を収めています。自信を持って前進できる時期です。",
      detail_en: "Victory, success, public recognition, progress.",
    },
    reversed: {
      keywords_ja: "失敗、自信の喪失、プライドの傷",
      detail_ja: "期待していた成功が得られず、自信を失っている状態です。内なる強さを見つめ直しましょう。",
      detail_en: "Failure, lack of recognition, egotism.",
    },
  },
  {
    id: "wands-7",
    number: null,
    name: "Seven of Wands",
    name_ja: "ワンドの7",
    aliases: ["W7", "7W", "7 of wands", "ワンドの7"],
    upright: {
      keywords_ja: "防衛、持ち場を守る、困難への挑戦",
      detail_ja: "多くの挑戦や批判にさらされていますが、自分の信念を守り抜いています。粘り強さが鍵です。",
      detail_en: "Challenge, perseverance, defensive, maintaining position.",
    },
    reversed: {
      keywords_ja: "諦め、圧倒される、自信の欠如",
      detail_ja: "プレッシャーに負けて立場を手放しそうになっています。自分の価値を信じることが必要です。",
      detail_en: "Giving up, overwhelmed, lack of confidence.",
    },
  },
  {
    id: "wands-8",
    number: null,
    name: "Eight of Wands",
    name_ja: "ワンドの8",
    aliases: ["W8", "8W", "8 of wands", "ワンドの8"],
    upright: {
      keywords_ja: "素早い行動、勢い、旅",
      detail_ja: "物事が急速に動き始め、目標に向かって一直線に進んでいます。旅や伝達にも関係します。",
      detail_en: "Speed, action, air travel, movement, swift change.",
    },
    reversed: {
      keywords_ja: "遅延、散漫、計画の乱れ",
      detail_ja: "エネルギーが分散し、物事が思うように進みません。落ち着いて優先順位を整理しましょう。",
      detail_en: "Delays, frustration, chaos, scattered energy.",
    },
  },
  {
    id: "wands-9",
    number: null,
    name: "Nine of Wands",
    name_ja: "ワンドの9",
    aliases: ["W9", "9W", "9 of wands", "ワンドの9"],
    upright: {
      keywords_ja: "回復力、粘り強さ、用心",
      detail_ja: "傷を負いながらも最後の力を振り絞っています。もう少しで目標に届くところです。警戒を緩めないで。",
      detail_en: "Resilience, persistence, test of faith, boundaries.",
    },
    reversed: {
      keywords_ja: "頑固さ、燃え尽き、降参",
      detail_ja: "疲れ果てて諦めの気持ちが生じています。それとも不必要に防衛的になりすぎていませんか。",
      detail_en: "Stubbornness, defensiveness, giving up.",
    },
  },
  {
    id: "wands-10",
    number: null,
    name: "Ten of Wands",
    name_ja: "ワンドの10",
    aliases: ["W10", "10W", "10 of wands", "ワンドの10"],
    upright: {
      keywords_ja: "重荷、責任過多、燃え尽き",
      detail_ja: "多くの責任を一人で抱え込みすぎています。目標はもうすぐそこですが、負担が重すぎる状態です。",
      detail_en: "Burden, extra responsibility, hard work, completion.",
    },
    reversed: {
      keywords_ja: "重荷の解放、委任、諦め",
      detail_ja: "ようやく重荷を手放し始めています。人に任せることや優先順位を見直すことが大切です。",
      detail_en: "Doing it all alone, collapse, releasing burden.",
    },
  },
  {
    id: "wands-page",
    number: null,
    name: "Page of Wands",
    name_ja: "ワンドのペイジ",
    aliases: ["WPa", "PaW", "page of wands", "ワンドのペイジ"],
    upright: {
      keywords_ja: "熱意、探索、自由な精神",
      detail_ja: "新しいことに興味を持ち、何でも試してみようとするエネルギーに満ちた姿勢です。",
      detail_en: "Enthusiasm, exploration, discovery, free spirit.",
    },
    reversed: {
      keywords_ja: "短気、信頼性の欠如、生意気",
      detail_ja: "良いアイデアはあるが実行力や忍耐力が伴わない状態です。一つのことに集中しましょう。",
      detail_en: "Hasty, impatient, lack of direction.",
    },
  },
  {
    id: "wands-knight",
    number: null,
    name: "Knight of Wands",
    name_ja: "ワンドのナイト",
    aliases: ["WKn", "KnW", "knight of wands", "ワンドのナイト"],
    upright: {
      keywords_ja: "行動力、冒険、衝動的",
      detail_ja: "情熱のまま猛スピードで突き進む人物やエネルギーを表します。大胆さが強みですが計画性が必要です。",
      detail_en: "Action, adventure, fearlessness, energy.",
    },
    reversed: {
      keywords_ja: "無謀、短気、計画性の欠如",
      detail_ja: "衝動的な行動や無計画な突進が問題を引き起こしています。立ち止まって考える時間が必要です。",
      detail_en: "Reckless, scattered, delays, frustration.",
    },
  },
  {
    id: "wands-queen",
    number: null,
    name: "Queen of Wands",
    name_ja: "ワンドのクイーン",
    aliases: ["WQ", "QW", "queen of wands", "ワンドのクイーン"],
    upright: {
      keywords_ja: "自信、魅力、情熱、外向的",
      detail_ja: "自分の力を信じ、周囲を明るく照らすカリスマ的な存在です。多くのことをこなしながらも優雅さを保ちます。",
      detail_en: "Confidence, independence, social, passionate.",
    },
    reversed: {
      keywords_ja: "嫉妬、わがまま、不安",
      detail_ja: "内なる不安から攻撃的または支配的な態度が出ています。自分への信頼を取り戻すことが大切です。",
      detail_en: "Demanding, jealousy, self-doubt.",
    },
  },
  {
    id: "wands-king",
    number: null,
    name: "King of Wands",
    name_ja: "ワンドのキング",
    aliases: ["WK", "KW", "king of wands", "ワンドのキング"],
    upright: {
      keywords_ja: "ビジョン、リーダーシップ、起業家精神",
      detail_ja: "大きなビジョンを持ち、それを実現に向けて周囲を率いる力強いリーダーです。",
      detail_en: "Natural leader, vision, entrepreneur, honour.",
    },
    reversed: {
      keywords_ja: "横暴、横柄、無責任なリーダー",
      detail_ja: "権力を乱用したり、自分の利益だけを追求するリーダーシップの歪みを示しています。",
      detail_en: "Forceful, domineering, tyrant.",
    },
  },

  // ── CUPS ───────────────────────────────────────────────────────────────
  {
    id: "cups-ace",
    number: null,
    name: "Ace of Cups",
    name_ja: "カップのエース",
    aliases: ["AC", "CA", "C1", "1C", "ace of cups", "カップのエース"],
    upright: {
      keywords_ja: "新しい愛、感情の豊かさ、直感",
      detail_ja: "愛情や喜び、霊的なつながりが新たに始まる予感です。心を開いて受け取る準備をしましょう。",
      detail_en: "New love, compassion, creativity, overwhelming emotion.",
    },
    reversed: {
      keywords_ja: "感情の抑圧、空虚感、内なるブロック",
      detail_ja: "感情を表現できず内に抑え込んでいる状態です。自分の気持ちと向き合う時間が必要です。",
      detail_en: "Blocked emotions, emptiness, repressed feelings.",
    },
  },
  {
    id: "cups-2",
    number: null,
    name: "Two of Cups",
    name_ja: "カップの2",
    aliases: ["C2", "2C", "2 of cups", "カップの2"],
    upright: {
      keywords_ja: "パートナーシップ、引き合い、相互の愛",
      detail_ja: "二人の間に強い絆と相互理解が生まれています。恋愛だけでなく深い友情や協力関係にも当てはまります。",
      detail_en: "Unified love, partnership, mutual attraction.",
    },
    reversed: {
      keywords_ja: "不調和、別れ、信頼の崩れ",
      detail_ja: "関係にひびが入り、互いの理解が難しくなっています。コミュニケーションの見直しが必要です。",
      detail_en: "Imbalance, broken communication, distrust.",
    },
  },
  {
    id: "cups-3",
    number: null,
    name: "Three of Cups",
    name_ja: "カップの3",
    aliases: ["C3", "3C", "3 of cups", "カップの3"],
    upright: {
      keywords_ja: "友情、お祝い、喜びの共有",
      detail_ja: "仲間と共に喜びを分かち合う祝祭の時です。コミュニティや友情のつながりが強まっています。",
      detail_en: "Celebration, friendship, creativity, community.",
    },
    reversed: {
      keywords_ja: "過剰な享楽、孤立、三角関係",
      detail_ja: "楽しみが過ぎてバランスを失っているか、グループから疎外感を感じている状態です。",
      detail_en: "Overindulgence, gossip, isolation, exclusion.",
    },
  },
  {
    id: "cups-4",
    number: null,
    name: "Four of Cups",
    name_ja: "カップの4",
    aliases: ["C4", "4C", "4 of cups", "カップの4"],
    upright: {
      keywords_ja: "瞑想、無関心、内省",
      detail_ja: "目の前の機会に気づかず、内向きになりすぎている状態です。新しい視点を持つことで展望が開けます。",
      detail_en: "Apathy, contemplation, disconnected, reevaluation.",
    },
    reversed: {
      keywords_ja: "新しい視点、行動への準備、内省からの脱却",
      detail_ja: "停滞から抜け出し、新たな可能性に目を向けようとしています。行動を起こす準備が整いつつあります。",
      detail_en: "Sudden awareness, new opportunities, re-engagement.",
    },
  },
  {
    id: "cups-5",
    number: null,
    name: "Five of Cups",
    name_ja: "カップの5",
    aliases: ["C5", "5C", "5 of cups", "カップの5"],
    upright: {
      keywords_ja: "喪失、悲しみ、後悔",
      detail_ja: "失ったものへの悲しみに目が向いていますが、まだ残っているものもあります。悲しみを認めながら前を向く時です。",
      detail_en: "Regret, failure, disappointment, grief.",
    },
    reversed: {
      keywords_ja: "回復、許し、前向きな姿勢",
      detail_ja: "悲しみから立ち直り、過去を受け入れて前進しようとしています。許しと癒しの時期です。",
      detail_en: "Moving on, acceptance, forgiveness.",
    },
  },
  {
    id: "cups-6",
    number: null,
    name: "Six of Cups",
    name_ja: "カップの6",
    aliases: ["C6", "6C", "6 of cups", "カップの6"],
    upright: {
      keywords_ja: "郷愁、無邪気さ、過去との再会",
      detail_ja: "懐かしい思い出や幼い頃の純粋さに思いを馳せています。過去からの贈り物や再会の可能性もあります。",
      detail_en: "Nostalgia, happy memories, reunion, innocence.",
    },
    reversed: {
      keywords_ja: "過去への執着、現実逃避、成長の拒否",
      detail_ja: "過去に生きすぎて現在を見失っています。前に進むためには過去を手放すことが必要です。",
      detail_en: "Stuck in the past, naivety, unrealistic.",
    },
  },
  {
    id: "cups-7",
    number: null,
    name: "Seven of Cups",
    name_ja: "カップの7",
    aliases: ["C7", "7C", "7 of cups", "カップの7"],
    upright: {
      keywords_ja: "幻想、多くの選択肢、夢想",
      detail_ja: "多くの可能性や夢が目の前に広がっていますが、そのどれが現実的かを見極める必要があります。",
      detail_en: "Fantasy, illusion, wishful thinking, choices.",
    },
    reversed: {
      keywords_ja: "明晰さ、現実的な選択、幻想からの目覚め",
      detail_ja: "夢想から覚め、現実的な判断ができるようになってきました。一つの目標に集中する時です。",
      detail_en: "Clarity, choosing wisely, sobriety.",
    },
  },
  {
    id: "cups-8",
    number: null,
    name: "Eight of Cups",
    name_ja: "カップの8",
    aliases: ["C8", "8C", "8 of cups", "カップの8"],
    upright: {
      keywords_ja: "別れ、新たな旅立ち、手放す",
      detail_ja: "表面上は満たされているように見えるものから離れ、より深い意味を求めて旅立つ決断をしています。",
      detail_en: "Walking away, disillusionment, leaving behind.",
    },
    reversed: {
      keywords_ja: "踏みとどまる、恐怖、未練",
      detail_ja: "立ち去るべき状況から離れられずにいます。恐怖や未練が前進を妨げています。",
      detail_en: "Staying, avoidance, fear of moving on.",
    },
  },
  {
    id: "cups-9",
    number: null,
    name: "Nine of Cups",
    name_ja: "カップの9",
    aliases: ["C9", "9C", "9 of cups", "カップの9"],
    upright: {
      keywords_ja: "満足、幸福、願望成就",
      detail_ja: "望んでいたことが叶い、深い満足感と幸福感に満ちています。「願いのカード」とも呼ばれます。",
      detail_en: "Contentment, satisfaction, gratitude, wish fulfilled.",
    },
    reversed: {
      keywords_ja: "自己満足、物質主義、不満",
      detail_ja: "表面的な満足に留まり、本当の幸せを見失っているかもしれません。内なる充実を見つめ直しましょう。",
      detail_en: "Indulgence, greed, dissatisfaction.",
    },
  },
  {
    id: "cups-10",
    number: null,
    name: "Ten of Cups",
    name_ja: "カップの10",
    aliases: ["C10", "10C", "10 of cups", "カップの10"],
    upright: {
      keywords_ja: "家庭の幸福、永続する喜び、調和",
      detail_ja: "家族や愛する人たちとの深い幸福と調和を表す、感情的な充実の完成形です。",
      detail_en: "Harmony, marriage, happiness, alignment.",
    },
    reversed: {
      keywords_ja: "家庭内の不和、理想と現実のギャップ",
      detail_ja: "理想とする幸せな家庭と現実の間にギャップが生じています。関係の修復が必要かもしれません。",
      detail_en: "Misalignment, broken home, shattered dreams.",
    },
  },
  {
    id: "cups-page",
    number: null,
    name: "Page of Cups",
    name_ja: "カップのペイジ",
    aliases: ["CPa", "PaC", "page of cups", "カップのペイジ"],
    upright: {
      keywords_ja: "創造性、直感、感受性",
      detail_ja: "感情と創造力に富んだ若いエネルギーです。夢やメッセージを大切にし、直感に従いましょう。",
      detail_en: "Creative opportunities, intuitive messages, curiosity.",
    },
    reversed: {
      keywords_ja: "感情的な未熟さ、失望、創造性のブロック",
      detail_ja: "感情のコントロールが難しく、空想と現実の区別がつきにくい状態です。",
      detail_en: "Emotional immaturity, insecurity, disappointment.",
    },
  },
  {
    id: "cups-knight",
    number: null,
    name: "Knight of Cups",
    name_ja: "カップのナイト",
    aliases: ["CKn", "KnC", "knight of cups", "カップのナイト"],
    upright: {
      keywords_ja: "ロマンチック、理想主義、魅力的な誘い",
      detail_ja: "心に従って行動するロマンティックな理想主義者です。感情豊かで創造的な提案や誘いをもたらします。",
      detail_en: "Romance, charm, imagination, beauty.",
    },
    reversed: {
      keywords_ja: "気分屋、非現実的、感情的な操作",
      detail_ja: "感情が不安定で気まぐれな態度が問題を生んでいます。現実と理想のバランスが必要です。",
      detail_en: "Moodiness, overactive imagination, unrealistic.",
    },
  },
  {
    id: "cups-queen",
    number: null,
    name: "Queen of Cups",
    name_ja: "カップのクイーン",
    aliases: ["CQ", "QC", "queen of cups", "カップのクイーン"],
    upright: {
      keywords_ja: "感情的な安定、直感、思いやり",
      detail_ja: "深い感受性と直感を持ちながら、感情に流されず穏やかに周囲を支える存在です。",
      detail_en: "Compassion, calm, comfort, intuition.",
    },
    reversed: {
      keywords_ja: "感情的な不安定、依存、殉教者",
      detail_ja: "感情に振り回されたり、自分を犠牲にしすぎている状態です。自分自身のケアが必要です。",
      detail_en: "Martyrdom, insecurity, giving too much.",
    },
  },
  {
    id: "cups-king",
    number: null,
    name: "King of Cups",
    name_ja: "カップのキング",
    aliases: ["CK", "KC", "king of cups", "カップのキング"],
    upright: {
      keywords_ja: "感情的な成熟、思いやり、外交的",
      detail_ja: "深い感情を持ちながらもそれを賢くコントロールする成熟した人物です。温かく頼りになる存在です。",
      detail_en: "Emotional balance, generosity, diplomacy.",
    },
    reversed: {
      keywords_ja: "感情的な操作、不安定、冷淡",
      detail_ja: "感情を武器に使ったり、内側の不安を隠して冷たく振る舞っている状態を示します。",
      detail_en: "Emotional manipulation, moodiness, volatility.",
    },
  },

  // ── SWORDS ─────────────────────────────────────────────────────────────
  {
    id: "swords-ace",
    number: null,
    name: "Ace of Swords",
    name_ja: "ソードのエース",
    aliases: ["AS", "SA", "S1", "1S", "ace of swords", "ソードのエース"],
    upright: {
      keywords_ja: "突破口、明晰さ、真実",
      detail_ja: "鋭い知性と明晰な思考で真実を切り開く力が与えられています。新たな視点と知的な始まりの時です。",
      detail_en: "Breakthroughs, clarity, truth, new ideas.",
    },
    reversed: {
      keywords_ja: "混乱、残酷さ、誤った考え",
      detail_ja: "思考が混乱し、正しい判断ができていない状態です。情報を整理し直す必要があります。",
      detail_en: "Confusion, brutality, chaos, clouded judgment.",
    },
  },
  {
    id: "swords-2",
    number: null,
    name: "Two of Swords",
    name_ja: "ソードの2",
    aliases: ["S2", "2S", "2 of swords", "ソードの2"],
    upright: {
      keywords_ja: "膠着状態、困難な選択、真実から目を背ける",
      detail_ja: "二つの選択肢の間で身動きがとれない状態です。目を閉じて問題から逃げることはできません。",
      detail_en: "Difficult choices, indecision, stalemate.",
    },
    reversed: {
      keywords_ja: "情報の過多、混乱、選択の強要",
      detail_ja: "情報が多すぎて決断できないか、望まない選択を迫られています。",
      detail_en: "Information overload, indecision, confusion.",
    },
  },
  {
    id: "swords-3",
    number: null,
    name: "Three of Swords",
    name_ja: "ソードの3",
    aliases: ["S3", "3S", "3 of swords", "ソードの3"],
    upright: {
      keywords_ja: "悲しみ、裏切り、失恋",
      detail_ja: "心に深い痛みや悲しみを抱えています。つらい真実に直面する必要がありますが、癒しへの第一歩でもあります。",
      detail_en: "Heartbreak, grief, sorrow, betrayal.",
    },
    reversed: {
      keywords_ja: "回復、許し、否定",
      detail_ja: "悲しみから立ち直ろうとしているか、または痛みを認めることを拒んでいる状態です。",
      detail_en: "Recovery, forgiveness, moving on.",
    },
  },
  {
    id: "swords-4",
    number: null,
    name: "Four of Swords",
    name_ja: "ソードの4",
    aliases: ["S4", "4S", "4 of swords", "ソードの4"],
    upright: {
      keywords_ja: "休息、回復、一時停止",
      detail_ja: "激しい戦いの後、心身を休めて回復する時期です。静けさの中で次への力を蓄えましょう。",
      detail_en: "Rest, recovery, contemplation, sanctuary.",
    },
    reversed: {
      keywords_ja: "行動への復帰、落ち着きのなさ、燃え尽き",
      detail_ja: "休息が足りないまま動き始めていたり、じっとしていられない焦りを感じています。",
      detail_en: "Restlessness, burnout, lack of rest.",
    },
  },
  {
    id: "swords-5",
    number: null,
    name: "Five of Swords",
    name_ja: "ソードの5",
    aliases: ["S5", "5S", "5 of swords", "ソードの5"],
    upright: {
      keywords_ja: "対立、不名誉な勝利、利己的",
      detail_ja: "勝利を収めたかもしれませんが、その手段は正しかったでしょうか。本当の勝者は誰もいない戦いです。",
      detail_en: "Conflict, defeat, win at all costs.",
    },
    reversed: {
      keywords_ja: "和解、過去の葛藤からの脱却、後悔",
      detail_ja: "過去の対立から学び、和解や許しに向かおうとしています。",
      detail_en: "Reconciliation, moving past conflict, regret.",
    },
  },
  {
    id: "swords-6",
    number: null,
    name: "Six of Swords",
    name_ja: "ソードの6",
    aliases: ["S6", "6S", "6 of swords", "ソードの6"],
    upright: {
      keywords_ja: "移行、困難からの脱出、より良い未来へ",
      detail_ja: "苦しい状況から離れ、より安定した未来へと向かっています。完全ではないが前進しています。",
      detail_en: "Transition, change, moving on, healing.",
    },
    reversed: {
      keywords_ja: "変化への抵抗、逃げられない、精神的な重荷",
      detail_ja: "苦しい状況から抜け出せないでいるか、過去の問題を引きずったまま進もうとしています。",
      detail_en: "Resistance to change, unfinished business, unable to move on.",
    },
  },
  {
    id: "swords-7",
    number: null,
    name: "Seven of Swords",
    name_ja: "ソードの7",
    aliases: ["S7", "7S", "7 of swords", "ソードの7"],
    upright: {
      keywords_ja: "欺き、裏切り、狡猾な戦略",
      detail_ja: "正面突破ではなく、巧みな策略や回避によって状況を乗り切ろうとしています。誠実さに注意が必要です。",
      detail_en: "Betrayal, deception, getting away with something.",
    },
    reversed: {
      keywords_ja: "告白、誠実さの回復、後悔",
      detail_ja: "隠していたことを認め、正直に向き合おうとしています。過去の嘘から解放される可能性があります。",
      detail_en: "Coming clean, imposter syndrome, conscience.",
    },
  },
  {
    id: "swords-8",
    number: null,
    name: "Eight of Swords",
    name_ja: "ソードの8",
    aliases: ["S8", "8S", "8 of swords", "ソードの8"],
    upright: {
      keywords_ja: "束縛、自己制限、孤立",
      detail_ja: "実は自分で作り出した制限や思い込みに縛られています。目隠しを外せば道は開けています。",
      detail_en: "Restriction, imprisonment, self-victimization.",
    },
    reversed: {
      keywords_ja: "解放、自由の発見、制限からの脱却",
      detail_ja: "自分を縛っていた思い込みや制限から解放されつつあります。新しい可能性が見え始めています。",
      detail_en: "Self-acceptance, new perspective, freedom.",
    },
  },
  {
    id: "swords-9",
    number: null,
    name: "Nine of Swords",
    name_ja: "ソードの9",
    aliases: ["S9", "9S", "9 of swords", "ソードの9"],
    upright: {
      keywords_ja: "不安、悪夢、精神的苦痛",
      detail_ja: "深夜に目が覚めるような不安や恐怖が心を支配しています。現実よりも思考が状況を悪化させています。",
      detail_en: "Anxiety, worry, fear, nightmares.",
    },
    reversed: {
      keywords_ja: "不安からの解放、助けを求める、否定",
      detail_ja: "ようやく不安と向き合い乗り越えようとしているか、または問題を直視することを避けています。",
      detail_en: "Inner turmoil, releasing worry, learning to cope.",
    },
  },
  {
    id: "swords-10",
    number: null,
    name: "Ten of Swords",
    name_ja: "ソードの10",
    aliases: ["S10", "10S", "10 of swords", "ソードの10"],
    upright: {
      keywords_ja: "終わり、裏切り、痛みの底",
      detail_ja: "非常につらい結末や裏切りを経験しています。しかしこれ以上悪くなることはなく、夜明けは近いです。",
      detail_en: "Painful endings, betrayal, crisis, rock bottom.",
    },
    reversed: {
      keywords_ja: "回復、立ち直り、最悪期の脱出",
      detail_ja: "最も辛い時期を乗り越え、ゆっくりと回復しています。過去の傷を引きずりすぎないように。",
      detail_en: "Recovery, regeneration, resisting inevitable end.",
    },
  },
  {
    id: "swords-page",
    number: null,
    name: "Page of Swords",
    name_ja: "ソードのペイジ",
    aliases: ["SPa", "PaS", "page of swords", "ソードのペイジ"],
    upright: {
      keywords_ja: "知的好奇心、新しいアイデア、素早い思考",
      detail_ja: "鋭い観察力と旺盛な知的好奇心を持ったエネルギーです。情報を素早く取り入れ分析します。",
      detail_en: "New ideas, curiosity, thirst for knowledge.",
    },
    reversed: {
      keywords_ja: "噂話、軽率な言動、浅薄な思考",
      detail_ja: "思慮のない言動や噂が問題を起こしています。言葉の重さを意識する必要があります。",
      detail_en: "Haste, deception, manipulation.",
    },
  },
  {
    id: "swords-knight",
    number: null,
    name: "Knight of Swords",
    name_ja: "ソードのナイト",
    aliases: ["SKn", "KnS", "knight of swords", "ソードのナイト"],
    upright: {
      keywords_ja: "行動力、野心、直接的",
      detail_ja: "目標に向かって猛スピードで突進する知性と行動力を持った人物です。しかし衝動性に注意が必要です。",
      detail_en: "Ambitious, action-oriented, driven.",
    },
    reversed: {
      keywords_ja: "無謀、攻撃的、方向性の喪失",
      detail_ja: "勢いが行き過ぎて周囲を傷つけたり、方向性を見失って空回りしています。",
      detail_en: "Restless, unfocused, impulsive.",
    },
  },
  {
    id: "swords-queen",
    number: null,
    name: "Queen of Swords",
    name_ja: "ソードのクイーン",
    aliases: ["SQ", "QS", "queen of swords", "ソードのクイーン"],
    upright: {
      keywords_ja: "独立、明晰な思考、鋭い判断",
      detail_ja: "感情に流されず、鋭い知性と公正な判断力で物事を見通す強い人物です。自立と知性の象徴です。",
      detail_en: "Independent, unbiased judgement, clear boundaries.",
    },
    reversed: {
      keywords_ja: "冷淡、意地悪、悲観的",
      detail_ja: "知性が冷酷さや批判的な態度として現れています。痛みからくる防衛的な壁に注意しましょう。",
      detail_en: "Coldness, cruelty, bitterness.",
    },
  },
  {
    id: "swords-king",
    number: null,
    name: "King of Swords",
    name_ja: "ソードのキング",
    aliases: ["SK", "KS", "king of swords", "ソードのキング"],
    upright: {
      keywords_ja: "知性、権威、倫理的な判断",
      detail_ja: "高い知性と公正な判断力を持つ権威ある人物です。論理と倫理に基づいたリーダーシップを発揮します。",
      detail_en: "Mental clarity, intellectual power, authority.",
    },
    reversed: {
      keywords_ja: "権力の乱用、冷酷、操作",
      detail_ja: "知性や権力を支配や操作のために使っています。独裁的な態度が周囲との摩擦を生んでいます。",
      detail_en: "Manipulative, ruthless, tyrannical.",
    },
  },

  // ── PENTACLES ──────────────────────────────────────────────────────────
  {
    id: "pentacles-ace",
    number: null,
    name: "Ace of Pentacles",
    name_ja: "ペンタクルのエース",
    aliases: ["AP", "PA", "P1", "1P", "ace of pentacles", "ペンタクルのエース"],
    upright: {
      keywords_ja: "新しい機会、物質的な豊かさ、安定の始まり",
      detail_ja: "金銭的・物質的な新しいチャンスが訪れています。現実的な豊かさの種が蒔かれる時です。",
      detail_en: "New financial opportunity, manifestation, abundance.",
    },
    reversed: {
      keywords_ja: "機会の損失、物質主義、計画の欠如",
      detail_ja: "せっかくの機会を活かせていないか、物質的なことへの執着が問題を生んでいます。",
      detail_en: "Lost opportunity, scarcity mindset, poor planning.",
    },
  },
  {
    id: "pentacles-2",
    number: null,
    name: "Two of Pentacles",
    name_ja: "ペンタクルの2",
    aliases: ["P2", "2P", "2 of pentacles", "ペンタクルの2"],
    upright: {
      keywords_ja: "バランス、優先順位、変化への適応",
      detail_ja: "複数のことを同時にこなしながらバランスを保っています。柔軟性と適応力が問われる時期です。",
      detail_en: "Multiple priorities, time management, adaptability.",
    },
    reversed: {
      keywords_ja: "混乱、過負荷、財政的な不安定",
      detail_ja: "バランスが崩れ、あれこれを抱えすぎて機能不全になっています。優先順位の整理が必要です。",
      detail_en: "Disorganized, overwhelmed, financial difficulty.",
    },
  },
  {
    id: "pentacles-3",
    number: null,
    name: "Three of Pentacles",
    name_ja: "ペンタクルの3",
    aliases: ["P3", "3P", "3 of pentacles", "ペンタクルの3"],
    upright: {
      keywords_ja: "チームワーク、技術の習得、協力",
      detail_ja: "それぞれの専門技術を持ち寄り、協力して質の高い成果を生み出しています。学びと実践の時です。",
      detail_en: "Teamwork, initial fulfilment, collaboration.",
    },
    reversed: {
      keywords_ja: "不一致、独りよがり、怠慢",
      detail_ja: "チームでの協力がうまくいかず、バラバラな方向に進んでいます。コミュニケーションの改善が必要です。",
      detail_en: "Misalignment, lack of teamwork, poor quality.",
    },
  },
  {
    id: "pentacles-4",
    number: null,
    name: "Four of Pentacles",
    name_ja: "ペンタクルの4",
    aliases: ["P4", "4P", "4 of pentacles", "ペンタクルの4"],
    upright: {
      keywords_ja: "安定、節約、执着",
      detail_ja: "持っているものをしっかりと守ろうとしています。安定は大切ですが、過度の執着は成長を妨げます。",
      detail_en: "Conservation, security, frugality.",
    },
    reversed: {
      keywords_ja: "物への執着の解放、気前よさ、財政的な不安定",
      detail_ja: "物やお金への執着を手放し始めるか、逆に財政管理が崩れている状態を示します。",
      detail_en: "Over-spending, greed, materialism.",
    },
  },
  {
    id: "pentacles-5",
    number: null,
    name: "Five of Pentacles",
    name_ja: "ペンタクルの5",
    aliases: ["P5", "5P", "5 of pentacles", "ペンタクルの5"],
    upright: {
      keywords_ja: "貧困、孤立、困難",
      detail_ja: "経済的・精神的な困難を経験しています。助けを求めることへの抵抗が孤立をさらに深めています。",
      detail_en: "Financial loss, poverty, lack mindset, isolation.",
    },
    reversed: {
      keywords_ja: "回復、援助の受け入れ、精神的な豊かさ",
      detail_ja: "困難な状況から回復しつつあります。外からの助けや内なる豊かさを受け入れましょう。",
      detail_en: "Recovery, charity, improving circumstances.",
    },
  },
  {
    id: "pentacles-6",
    number: null,
    name: "Six of Pentacles",
    name_ja: "ペンタクルの6",
    aliases: ["P6", "6P", "6 of pentacles", "ペンタクルの6"],
    upright: {
      keywords_ja: "寛大さ、施し、公平な分配",
      detail_ja: "持っているものを分かち合い、他者を助けることができる立場にあります。与えることと受け取ることのバランスです。",
      detail_en: "Giving, receiving, generosity, sharing.",
    },
    reversed: {
      keywords_ja: "見返りを求める施し、不公平、借金",
      detail_ja: "表向きは寛大に見えて実は見返りを期待していたり、力の不均衡が問題になっています。",
      detail_en: "Strings attached, power dynamics, debt.",
    },
  },
  {
    id: "pentacles-7",
    number: null,
    name: "Seven of Pentacles",
    name_ja: "ペンタクルの7",
    aliases: ["P7", "7P", "7 of pentacles", "ペンタクルの7"],
    upright: {
      keywords_ja: "忍耐、長期投資、立ち止まって見直す",
      detail_ja: "これまでの努力を振り返り、成果を確認する時期です。長期的な視点で継続することが大切です。",
      detail_en: "Long-term view, sustainable results, perseverance.",
    },
    reversed: {
      keywords_ja: "焦り、短期思考、努力への疑念",
      detail_ja: "すぐに結果が出ないことへの苛立ちや、これまでの努力が無駄だったのかという疑念が生じています。",
      detail_en: "Lack of long-term vision, impatience.",
    },
  },
  {
    id: "pentacles-8",
    number: null,
    name: "Eight of Pentacles",
    name_ja: "ペンタクルの8",
    aliases: ["P8", "8P", "8 of pentacles", "ペンタクルの8"],
    upright: {
      keywords_ja: "職人技、技術の向上、勤勉",
      detail_ja: "一つのことに集中して技術を磨き、着実に成長しています。努力と練習の積み重ねが実を結びます。",
      detail_en: "Diligence, mastery, skill development.",
    },
    reversed: {
      keywords_ja: "単調な作業、向上心の欠如、手抜き",
      detail_ja: "やる気を失い、作業が機械的になっています。目標を見失わないように振り返りましょう。",
      detail_en: "Lack of motivation, mediocrity, poor work ethic.",
    },
  },
  {
    id: "pentacles-9",
    number: null,
    name: "Nine of Pentacles",
    name_ja: "ペンタクルの9",
    aliases: ["P9", "9P", "9 of pentacles", "ペンタクルの9"],
    upright: {
      keywords_ja: "豊かさ、自立、自己充足",
      detail_ja: "自分の努力で築いた豊かさと自立を楽しんでいます。優雅に自分の成果を享受できる時期です。",
      detail_en: "Abundance, luxury, self-reliance, financial independence.",
    },
    reversed: {
      keywords_ja: "過度の依存、見せかけの豊かさ、自己投資の不足",
      detail_ja: "外見上は豊かに見えても内実が伴っていないか、自分自身への投資を怠っています。",
      detail_en: "Over-investment in work, financial setbacks.",
    },
  },
  {
    id: "pentacles-10",
    number: null,
    name: "Ten of Pentacles",
    name_ja: "ペンタクルの10",
    aliases: ["P10", "10P", "10 of pentacles", "ペンタクルの10"],
    upright: {
      keywords_ja: "永続する豊かさ、家族の遺産、長期的な安定",
      detail_ja: "家族や共同体を通じた豊かさと安定の完成形です。次世代に受け継がれる豊かな遺産を表します。",
      detail_en: "Legacy, culmination, inheritance, affluence.",
    },
    reversed: {
      keywords_ja: "財政的な失敗、家族の問題、不安定な基盤",
      detail_ja: "築いてきたものが崩れたり、家族や遺産にまつわる問題が生じています。",
      detail_en: "Financial failure, family disputes, instability.",
    },
  },
  {
    id: "pentacles-page",
    number: null,
    name: "Page of Pentacles",
    name_ja: "ペンタクルのペイジ",
    aliases: ["PPa", "PaP", "page of pentacles", "ペンタクルのペイジ"],
    upright: {
      keywords_ja: "勤勉、新しいスキルの習得、目標への集中",
      detail_ja: "現実的な目標に向かって着実に学び成長しようとしているエネルギーです。新しいスキルの始まりです。",
      detail_en: "Manifestation, financial opportunity, new skills.",
    },
    reversed: {
      keywords_ja: "集中力の欠如、浪費、怠慢",
      detail_ja: "目標はあるが行動が伴わず、機会を無駄にしています。現実的な一歩を踏み出しましょう。",
      detail_en: "Procrastination, lack of progress, poor focus.",
    },
  },
  {
    id: "pentacles-knight",
    number: null,
    name: "Knight of Pentacles",
    name_ja: "ペンタクルのナイト",
    aliases: ["PKn", "KnP", "knight of pentacles", "ペンタクルのナイト"],
    upright: {
      keywords_ja: "責任感、着実、効率",
      detail_ja: "急がず焦らず、着実に目標に向かって進む信頼できる人物やエネルギーです。継続と責任が強みです。",
      detail_en: "Hard work, efficiency, routine, conservatism.",
    },
    reversed: {
      keywords_ja: "退屈、停滞、完璧主義",
      detail_ja: "慎重すぎて動きが止まっていたり、変化を恐れて同じ場所に留まり続けています。",
      detail_en: "Boredom, stagnation, perfectionism.",
    },
  },
  {
    id: "pentacles-queen",
    number: null,
    name: "Queen of Pentacles",
    name_ja: "ペンタクルのクイーン",
    aliases: ["PQ", "QP", "queen of pentacles", "ペンタクルのクイーン"],
    upright: {
      keywords_ja: "実用的、豊か、思いやり、自立",
      detail_ja: "物質的な豊かさと温かい思いやりを兼ね備えた存在です。家庭と仕事の両立を見事にこなします。",
      detail_en: "Practical, ambitious, nurturing, resourceful.",
    },
    reversed: {
      keywords_ja: "仕事への没頭、嫉妬、自己中心",
      detail_ja: "物質的なことや仕事に没頭しすぎて、人間関係や内面の豊かさが疎かになっています。",
      detail_en: "Smothering, jealousy, insecurity.",
    },
  },
  {
    id: "pentacles-king",
    number: null,
    name: "King of Pentacles",
    name_ja: "ペンタクルのキング",
    aliases: ["PK", "KP", "king of pentacles", "ペンタクルのキング"],
    upright: {
      keywords_ja: "豊かさ、ビジネスの成功、信頼性、安定",
      detail_ja: "長年の努力と賢明な判断で物質的な成功を収めた、頼りになる人物です。安定と豊かさの象徴です。",
      detail_en: "Wealth, business, stability, security, abundance.",
    },
    reversed: {
      keywords_ja: "物質主義、強欲、頑固",
      detail_ja: "物質的な成功に固執しすぎて、精神的な豊かさや人間関係を犠牲にしています。",
      detail_en: "Greed, indulgence, materialism.",
    },
  },
];
